# Generated by Django 5.2.6 on 2025-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief professional summary', null=True),
        ),
    ]
